module.exports = {
  addMultiSigAddress: 'addmultisigaddress',
  addNode: 'addnode', 
  backupWallet: 'backupwallet',
  banNode: 'bannode',
  checkWallet: 'checkwallet',
  createMultiSig: 'createmultisig',
  createRawTransaction: 'createrawtransaction', 
  decodeRawTransaction: 'decoderawtransaction', 
  dumpPrivKey: 'dumpprivkey',
  encryptWallet: 'encryptwallet',
  executeAdvertiseBeacon: 'execute advertisebeacon',
  executeBeaconReport: 'execute beaconreport',
  executeGatherNeuralHashes: 'execute gatherneuralhashes',
  executeNeuralRequest: 'execute neuralrequest',
  executeReboot: 'execute reboot',
  executeRestorePoint: 'execute restorepoint',
  executeSyncDPOR2: 'execute syncdpor2',
  executeNeuralReport: 'execute neuralreport',
  executeMyNeuralHash: 'execute myneuralhash',
  executeSuperBlockAge: 'execute superblockage',
  executeNeuralHash: 'execute neuralhash',
  executeVote: 'execute vote',
  executeAddPoll: 'execute addpoll',
  executeVoteDetails: 'execute votedetails',
  executeListPolls: 'execute listpolls',
  executeListPollDetails: 'execute listpolldetails',
  executeListPollResults: 'execute listpollresults',
  executeTestNewContract: 'execute testnewcontract',
  executeRAC: 'execute rac',
  executeEncrypt: 'execute encrypt',
  executeTestBOINCKey: 'execute testboinckey',
  executeGenBOINCKey: 'execute genboinckey',
  executeWCGTesT: 'execute wcgtest',
  executeSyncRAC: 'execute syncrac',
  executeDPORTally: 'execute dportally',
  executeGetListOf: 'execute getlistof',
  executeListData: 'execute listdata',
  executeVolatileCode: 'execute volatilecode',
  executeStartWireFrame: 'execute startwireframe',
  executeTally: 'execute tally',
  executeTestHash: 'execute testhash',
  executeResetCPIDs: 'execute resetcpids',
  executeBackupWallet: 'execute backupwallet',
  executeRestoreWallet: 'execute restorewallet',
  executeResendWalletTX: 'execute resendwallettx',
  executePostCPID: 'execute postcpid',
  executeEncrypt_Deprecated: 'execute encrypt_deprecated',
  executeFindRAC: 'execute findrac',
  getAccount: 'getaccount',
  getAccountAddress: 'getaccountaddress',
  getAddedNodeInfo: 'getaddednodeinfo', 
  getAddressesByAccount: 'getaddressesbyaccount',
  getBalance: 'getbalance',
  getBlock: 'getblock',
  getblockbynumber: 'getblockbynumber',
  getBlockCount: 'getblockcount',
  getBlockHash: 'getblockhash',
  getBlockTemplate: 'getblocktemplate', 
  getConnectionCount: 'getconnectioncount',
  getDifficulty: 'getdifficulty',
  getInfo: 'getinfo',
  getMiningInfo: 'getmininginfo',
  getNewAddress: 'getnewaddress',
  getPeerInfo: 'getpeerinfo',
  getRawChangeAddress: 'getrawchangeaddress',
  getRawMemPool: 'getrawmempool', 
  getRawTransaction: 'getrawtransaction',
  getReceivedByAccount: 'getreceivedbyaccount',
  getReceivedByAddress: 'getreceivedbyaddress',
  getStakingInfo: 'getstakinginfo',
  getTransaction: 'gettransaction',
  getTxOut: 'gettxout', 
  getTxOutSetInfo: 'gettxoutsetinfo', 
  getWork: 'getwork',
  help: 'help',
  importPrivKey: 'importprivkey',
  keypoolRefill: 'keypoolrefill',
  keyPoolRefill: 'keypoolrefill',
  listAccounts: 'listaccounts',
  listAddressGroupings: 'listaddressgroupings', 
  listBannedNodes: 'listbannednodes',
  listCPIDS: 'list cpids',
  listExplainMagnitude: 'list explainmagnitude',
  listLockUnspent: 'listlockunspent',
  listMagnitude: 'list magnitude',
  listMagnitudeCSV: 'list magnitudecsv',
  listMyMagnitude: 'list mymagnitude',
  listNetwork: 'list network',
  listNetworkTime: 'list networktime',
  listRSAWeight: 'list rsaweight',
  listLottery: 'list lottery',
  listDebug3: 'list debug3',
  listCurrentTime: 'list currenttime',
  listOpenContracts: 'list opencontracts',
  listDetailMagnitudeCSV: 'list detailmagnitudecsv',
  listleder: 'list leder',
  listProjects: 'list projects',
  listReceivedByAccount: 'listreceivedbyaccount',
  listReceivedByAddress: 'listreceivedbyaddress',
  listResetCPIDs: 'list resetcpids',
  listRSA: 'list rsa',
  listRSAWeight: 'list rsaweight',
  listSinceBlock: 'listsinceblock',
  listTransactions: 'listtransactions',
  listUnspent: 'listunspent', 
  lockUnspent: 'lockunspent',
  listValidCPIDS: 'list validcpids',
  move: 'move',
  repairWallet: 'repairwallet',
  sendFrom: 'sendfrom',
  sendMany: 'sendmany',
  sendRawTransaction: 'sendrawtransaction', 
  sendToAddress: 'sendtoaddress',
  setAccount: 'setaccount',
  setGenerate: 'setgenerate',
  setMinInput: 'setmininput',
  setTxFee: 'settxfee',
  signMessage: 'signmessage',
  signRawTransaction: 'signrawtransaction', 
  stop: 'stop',
  submitBlock: 'submitblock', 
  validateAddress: 'validateaddress',
  verifyMessage: 'verifymessage',
  walletLock: 'walletlock',
  walletPassphrase: 'walletpassphrase',
  walletPassphraseChange: 'walletpassphrasechange'
};